2023-06-18 21:13:01,182 INFO    StreamThr :11866 [internal.py:wandb_internal():86] W&B internal server running at pid: 11866, started at: 2023-06-18 21:13:01.181445
2023-06-18 21:13:01,185 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: status
2023-06-18 21:13:01,188 INFO    WriterThread:11866 [datastore.py:open_for_write():85] open: /home/admin/startup_assignments/enterpret/code/wandb/run-20230618_211254-ybdaawj5/run-ybdaawj5.wandb
2023-06-18 21:13:01,192 DEBUG   SenderThread:11866 [sender.py:send():369] send: header
2023-06-18 21:13:01,192 DEBUG   SenderThread:11866 [sender.py:send():369] send: run
2023-06-18 21:13:02,136 INFO    SenderThread:11866 [dir_watcher.py:__init__():211] watching files in: /home/admin/startup_assignments/enterpret/code/wandb/run-20230618_211254-ybdaawj5/files
2023-06-18 21:13:02,136 INFO    SenderThread:11866 [sender.py:_start_run_threads():1100] run started: ybdaawj5 with start time 1687102980.33753
2023-06-18 21:13:02,151 DEBUG   SenderThread:11866 [sender.py:send_request():396] send_request: summary_record
2023-06-18 21:13:02,152 INFO    SenderThread:11866 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-06-18 21:13:02,160 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: check_version
2023-06-18 21:13:02,161 DEBUG   SenderThread:11866 [sender.py:send_request():396] send_request: check_version
2023-06-18 21:13:02,277 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: run_start
2023-06-18 21:13:02,278 DEBUG   HandlerThread:11866 [system_info.py:__init__():31] System info init
2023-06-18 21:13:02,279 DEBUG   HandlerThread:11866 [system_info.py:__init__():46] System info init done
2023-06-18 21:13:02,279 INFO    HandlerThread:11866 [system_monitor.py:start():181] Starting system monitor
2023-06-18 21:13:02,280 INFO    SystemMonitor:11866 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-06-18 21:13:02,281 INFO    HandlerThread:11866 [system_monitor.py:probe():201] Collecting system info
2023-06-18 21:13:02,282 INFO    SystemMonitor:11866 [interfaces.py:start():190] Started cpu monitoring
2023-06-18 21:13:02,284 INFO    SystemMonitor:11866 [interfaces.py:start():190] Started disk monitoring
2023-06-18 21:13:02,286 INFO    SystemMonitor:11866 [interfaces.py:start():190] Started memory monitoring
2023-06-18 21:13:02,289 INFO    SystemMonitor:11866 [interfaces.py:start():190] Started network monitoring
2023-06-18 21:13:02,345 DEBUG   HandlerThread:11866 [system_info.py:probe():195] Probing system
2023-06-18 21:13:02,347 DEBUG   HandlerThread:11866 [system_info.py:_probe_git():180] Probing git
2023-06-18 21:13:02,364 DEBUG   HandlerThread:11866 [system_info.py:_probe_git():188] Probing git done
2023-06-18 21:13:02,364 DEBUG   HandlerThread:11866 [system_info.py:probe():240] Probing system done
2023-06-18 21:13:02,364 DEBUG   HandlerThread:11866 [system_monitor.py:probe():210] {'os': 'Linux-5.15.0-75-generic-x86_64-with-glibc2.31', 'python': '3.10.4', 'heartbeatAt': '2023-06-18T15:43:02.345517', 'startedAt': '2023-06-18T15:42:54.468228', 'docker': None, 'cuda': None, 'args': None, 'state': 'running', 'program': '<python with no main file>', 'git': {'remote': 'https://github.com/VirajBagal/enterpret_summarizer.git', 'commit': 'ca554ac4329c3cf8b9b5861edd9ca947a17183c4'}, 'email': 'virajbagal12@gmail.com', 'root': '/home/admin/startup_assignments/enterpret', 'host': 'viraj-HP-Laptop-15q-ds1xxx', 'username': 'admin', 'executable': '/home/admin/anaconda3/envs/beast/bin/python', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 1994.1963750000002, 'min': 400.0, 'max': 3900.0}, 'cpu_freq_per_core': [{'current': 1041.781, 'min': 400.0, 'max': 3900.0}, {'current': 1014.806, 'min': 400.0, 'max': 3900.0}, {'current': 1800.0, 'min': 400.0, 'max': 3900.0}, {'current': 1800.0, 'min': 400.0, 'max': 3900.0}, {'current': 1800.0, 'min': 400.0, 'max': 3900.0}, {'current': 1800.0, 'min': 400.0, 'max': 3900.0}, {'current': 1800.0, 'min': 400.0, 'max': 3900.0}, {'current': 1800.0, 'min': 400.0, 'max': 3900.0}], 'disk': {'total': 233.17998886108398, 'used': 217.4363250732422}, 'memory': {'total': 15.503009796142578}}
2023-06-18 21:13:02,364 INFO    HandlerThread:11866 [system_monitor.py:probe():211] Finished collecting system info
2023-06-18 21:13:02,365 INFO    HandlerThread:11866 [system_monitor.py:probe():214] Publishing system info
2023-06-18 21:13:02,365 DEBUG   HandlerThread:11866 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-06-18 21:13:02,366 DEBUG   HandlerThread:11866 [system_info.py:_save_pip():67] Saving pip packages done
2023-06-18 21:13:02,366 DEBUG   HandlerThread:11866 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-06-18 21:13:03,137 INFO    Thread-50 :11866 [dir_watcher.py:_on_file_created():272] file/dir created: /home/admin/startup_assignments/enterpret/code/wandb/run-20230618_211254-ybdaawj5/files/wandb-summary.json
2023-06-18 21:13:03,138 INFO    Thread-50 :11866 [dir_watcher.py:_on_file_created():272] file/dir created: /home/admin/startup_assignments/enterpret/code/wandb/run-20230618_211254-ybdaawj5/files/requirements.txt
2023-06-18 21:13:03,138 INFO    Thread-50 :11866 [dir_watcher.py:_on_file_created():272] file/dir created: /home/admin/startup_assignments/enterpret/code/wandb/run-20230618_211254-ybdaawj5/files/conda-environment.yaml
2023-06-18 21:13:09,138 INFO    Thread-50 :11866 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/admin/startup_assignments/enterpret/code/wandb/run-20230618_211254-ybdaawj5/files/conda-environment.yaml
2023-06-18 21:13:09,357 DEBUG   HandlerThread:11866 [system_info.py:_save_conda():86] Saving conda packages done
2023-06-18 21:13:09,357 INFO    HandlerThread:11866 [system_monitor.py:probe():216] Finished publishing system info
2023-06-18 21:13:09,358 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: status_report
2023-06-18 21:13:09,358 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: keepalive
2023-06-18 21:13:09,358 DEBUG   SenderThread:11866 [sender.py:send():369] send: files
2023-06-18 21:13:09,359 INFO    SenderThread:11866 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-06-18 21:13:09,383 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: stop_status
2023-06-18 21:13:09,384 DEBUG   SenderThread:11866 [sender.py:send_request():396] send_request: stop_status
2023-06-18 21:13:09,963 DEBUG   SenderThread:11866 [sender.py:send():369] send: telemetry
2023-06-18 21:13:10,036 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: log_artifact
2023-06-18 21:13:10,037 DEBUG   SenderThread:11866 [sender.py:send_request():396] send_request: log_artifact
2023-06-18 21:13:10,111 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: partial_history
2023-06-18 21:13:10,139 INFO    Thread-50 :11866 [dir_watcher.py:_on_file_created():272] file/dir created: /home/admin/startup_assignments/enterpret/code/wandb/run-20230618_211254-ybdaawj5/files/media/table/Test Predictions using Peft Flan-T5-Large Model_0_3469b7df9441efa1172d.table.json
2023-06-18 21:13:10,139 INFO    Thread-50 :11866 [dir_watcher.py:_on_file_created():272] file/dir created: /home/admin/startup_assignments/enterpret/code/wandb/run-20230618_211254-ybdaawj5/files/wandb-metadata.json
2023-06-18 21:13:10,140 INFO    Thread-50 :11866 [dir_watcher.py:_on_file_created():272] file/dir created: /home/admin/startup_assignments/enterpret/code/wandb/run-20230618_211254-ybdaawj5/files/media
2023-06-18 21:13:10,140 INFO    Thread-50 :11866 [dir_watcher.py:_on_file_created():272] file/dir created: /home/admin/startup_assignments/enterpret/code/wandb/run-20230618_211254-ybdaawj5/files/media/table
2023-06-18 21:13:10,238 INFO    wandb-upload_0:11866 [upload_job.py:push():133] Uploaded file /tmp/tmpgh3c49qywandb/a4d7npee-wandb-metadata.json
2023-06-18 21:13:12,749 INFO    wandb-upload_1:11866 [upload_job.py:push():133] Uploaded file /tmp/tmpgh3c49qywandb/vwiquck5-media/table/Test Predictions using Peft Flan-T5-Large Model_0_3469b7df9441efa1172d.table.json
2023-06-18 21:13:13,713 INFO    wandb-upload_0:11866 [upload_job.py:push():91] Uploaded file /home/admin/.local/share/wandb/artifacts/staging/tmp724t1cmr
2023-06-18 21:13:19,064 INFO    SenderThread:11866 [sender.py:send_request_log_artifact():1414] logged artifact run-ybdaawj5-TestPredictionsusingPeftFlanT5LargeModel - {'id': 'QXJ0aWZhY3Q6NDkxNTg4NTYw', 'digest': '490d17ab61de0e48e61b6cac9059cb9c', 'state': 'PENDING', 'aliases': [], 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjc3NjY4MTUy', 'latestArtifact': None}, 'version': 'latest'}
2023-06-18 21:13:19,065 DEBUG   SenderThread:11866 [sender.py:send():369] send: files
2023-06-18 21:13:19,065 INFO    SenderThread:11866 [sender.py:_save_file():1354] saving file media/table/Test Predictions using Peft Flan-T5-Large Model_0_3469b7df9441efa1172d.table.json with policy now
2023-06-18 21:13:19,066 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: status_report
2023-06-18 21:13:19,067 DEBUG   SenderThread:11866 [sender.py:send():369] send: history
2023-06-18 21:13:19,068 DEBUG   SenderThread:11866 [sender.py:send_request():396] send_request: summary_record
2023-06-18 21:13:19,074 INFO    SenderThread:11866 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-06-18 21:13:19,147 INFO    Thread-50 :11866 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/admin/startup_assignments/enterpret/code/wandb/run-20230618_211254-ybdaawj5/files/wandb-summary.json
2023-06-18 21:13:21,200 INFO    wandb-upload_1:11866 [upload_job.py:push():133] Uploaded file /tmp/tmpgh3c49qywandb/cmrjk2n7-media/table/Test Predictions using Peft Flan-T5-Large Model_0_3469b7df9441efa1172d.table.json
2023-06-18 21:13:24,076 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: status_report
2023-06-18 21:13:24,382 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: stop_status
2023-06-18 21:13:24,382 DEBUG   SenderThread:11866 [sender.py:send_request():396] send_request: stop_status
2023-06-18 21:13:29,656 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: status_report
2023-06-18 21:13:34,662 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: status_report
2023-06-18 21:13:35,161 INFO    Thread-50 :11866 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/admin/startup_assignments/enterpret/code/wandb/run-20230618_211254-ybdaawj5/files/config.yaml
2023-06-18 21:13:39,383 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: stop_status
2023-06-18 21:13:39,383 DEBUG   SenderThread:11866 [sender.py:send_request():396] send_request: stop_status
2023-06-18 21:13:40,658 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: status_report
2023-06-18 21:13:45,659 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: status_report
2023-06-18 21:13:50,661 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: status_report
2023-06-18 21:13:54,384 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: stop_status
2023-06-18 21:13:54,385 DEBUG   SenderThread:11866 [sender.py:send_request():396] send_request: stop_status
2023-06-18 21:13:56,658 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: status_report
2023-06-18 21:14:01,660 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: status_report
2023-06-18 21:14:02,290 DEBUG   SystemMonitor:11866 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-06-18 21:14:02,293 DEBUG   SenderThread:11866 [sender.py:send():369] send: stats
2023-06-18 21:14:07,295 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: status_report
2023-06-18 21:14:09,386 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: stop_status
2023-06-18 21:14:09,387 DEBUG   SenderThread:11866 [sender.py:send_request():396] send_request: stop_status
2023-06-18 21:14:12,670 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: status_report
2023-06-18 21:14:17,672 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: status_report
2023-06-18 21:14:22,673 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: status_report
2023-06-18 21:14:24,384 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: stop_status
2023-06-18 21:14:24,385 DEBUG   SenderThread:11866 [sender.py:send_request():396] send_request: stop_status
2023-06-18 21:14:29,387 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: keepalive
2023-06-18 21:14:34,388 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: keepalive
2023-06-18 21:14:38,014 INFO    SenderThread:11866 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fca245fcf10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca245fcf10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 320, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 55, in execute
    request = self.session.post(self.url, **post_args)
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/admin/anaconda3/envs/beast/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fca245fcf10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2023-06-18 21:14:39,390 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: keepalive
2023-06-18 21:14:44,392 DEBUG   HandlerThread:11866 [handler.py:handle_request():144] handle_request: keepalive
